### ISSUE TITLE
Tracking issue for Asset Locks implementation

### ISSUE THREAD

**Issue by knst** [darkcoin/darkcoin#5022]
## Tracking issue for Asset Locks implementation

Branch: https://github.com/knst/dash/tree/asset-locks

### Subtasks

- [x] Asset lock transaction implementation
- [x] Asset unlock transaction implementation
- [x] Unit tests for lock transaction implementation
- [x] Unit tests for unlock transaction implementation
-------
- [x] Validation for asset lock tx
- [x] Validation for asset unlock tx
- [x] Functional tests for lock transaction implementation
- [x] Functional tests for unlock transaction implementation
- [x] Credit Pool implementation [in progress]
- [x] Save credit-pool value to coinbase transaction
- [x] To discuss asset unlock (withdrawal) limitation and how to revert them
- [x] Asset unlock (withdrawal) limitations (maximum amount by last N blocks)
- [ ] Rpc for asset lock
- [ ] Rpc for asset unlock
- [x] Rpc for credit pool
- [x] fix `feature_llmq_is_cl_conflicts.py` and `feature_nulldummy.py`  functional tests
- [x] implement index validation (should not be duplicates)
- [x] implement tests for index duplicates
- [x] implement data structure SkipSet more efficient + unit tests for it
- [x] rebase starting from this commits https://github.com/dashpay/dash/pull/5070
